[package]
name = "wotto-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "wotto-repl"
path = "src/main.rs"

[dependencies]
wotto-engine = { path = "../wotto-engine", features = ["repl"] }
anyhow = "1.0"
tokio = "*"
